/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddPatient: typeof import('./src/components/Utilitaires/AddPatient.vue')['default']
    AddRDV: typeof import('./src/components/Utilitaires/AddRDV.vue')['default']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    Analyse: typeof import('./src/components/Consult/Analyse.vue')['default']
    Analyses: typeof import('./src/components/Folder/Analyses.vue')['default']
    AntAllergies: typeof import('./src/components/Folder/AntAllergies.vue')['default']
    AntChirurgicaux: typeof import('./src/components/Folder/AntChirurgicaux.vue')['default']
    AntDrugs: typeof import('./src/components/Folder/AntDrugs.vue')['default']
    Antecedents: typeof import('./src/components/Folder/Antecedents.vue')['default']
    AntFamiliaux: typeof import('./src/components/Folder/AntFamiliaux.vue')['default']
    AntMedicaux: typeof import('./src/components/Folder/AntMedicaux.vue')['default']
    Consultations: typeof import('./src/components/Folder/Consultations.vue')['default']
    Details: typeof import('./src/components/Consult/Details.vue')['default']
    Diagnostic: typeof import('./src/components/Consult/Diagnostic.vue')['default']
    EditEDV: typeof import('./src/components/Utilitaires/EditEDV.vue')['default']
    EditPatient: typeof import('./src/components/Utilitaires/EditPatient.vue')['default']
    ExamenPhysique: typeof import('./src/components/Consult/ExamenPhysique.vue')['default']
    Facture: typeof import('./src/components/Consult/Facture.vue')['default']
    Finance: typeof import('./src/components/Folder/Finance.vue')['default']
    Imagerie: typeof import('./src/components/Folder/Imagerie.vue')['default']
    Observation: typeof import('./src/components/Consult/Observation.vue')['default']
    Ordonnance: typeof import('./src/components/Consult/Ordonnance.vue')['default']
    Ordonnances: typeof import('./src/components/Folder/Ordonnances.vue')['default']
    RendezVous: typeof import('./src/components/Folder/RendezVous.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Soins: typeof import('./src/components/Consult/Soins.vue')['default']
    TableauPersonalise: typeof import('./src/components/Folder/TableauPersonalise.vue')['default']
    Tasks: typeof import('./src/components/Tasks.vue')['default']
    Traitement: typeof import('./src/components/Folder/Traitement.vue')['default']
    UiAccordion: typeof import('./src/components/Ui/ui-accordion.vue')['default']
    UiAgenda: typeof import('./src/components/Ui/ui-agenda.vue')['default']
    UiCard: typeof import('./src/components/Ui/ui-card.vue')['default']
    UiMenu: typeof import('./src/components/Ui/ui-menu.vue')['default']
    UiMenuAnt: typeof import('./src/components/Ui/ui-menu-ant.vue')['default']
    UiSheet: typeof import('./src/components/Ui/ui-sheet.vue')['default']
    UiTable: typeof import('./src/components/Ui/ui-table.vue')['default']
  }
}
